version: "3.8"

services:

  threelab-api:
    image: threelab-api:v1
    container_name: node-api
    build: 
       context: .
       dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PRO_APP_PORT:3058
      - PRO_DB_NAME:test
      - PRO_DB_HOST:mongo_db
      - PRO_DB_PORT:27017
    ports:
      - 4000:3058
    depends_on:
      - mongo_db
    networks:
      - nodejsapi-network


  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 2717:27017
    networks:
      - nodejsapi-network
    volumes:
      - db:/data/d

networks:
  nodejsapi-network:
    driver: bridge
volumes:
  db: {}


